### PR TITLE
Us5 access to contacts module

### PR DESCRIPTION
**Pull request by vidash50**
check the codes

### CODE REVIEW

**Review by EllaKoch — APPROVED** [review]
Looks Great!

**Comment by marwansubhi** [comment]
GTG

**Comment by anitastati** [comment]
good job

**Comment by KatrinSi** [comment]
Great job Vida!

**Comment by davisduane** [comment]
looks good

**Comment by miraysir** [comment]
Good job!!

**Review by anitastati — COMMENTED** [review]
good

**Review by KatrinSi — APPROVED** [review]

**Review by miraysir — APPROVED** [review]
Perfect

**Review by marwansubhi — APPROVED** [review]
Looks good

**Pull request merged**
