### PR TITLE
Us5 access contacts module

### PR DESCRIPTION
**Pull request by anitastati**
user story 5

### CODE REVIEW

**Review by Alex-Cret — APPROVED** [review]

**Review by marwansubhi — APPROVED** [review]
Looks good

**Review by EllaKoch — APPROVED** [review]
Looks great Ana!

**Review by EllaKoch — APPROVED** [review]
Looks great Ana!

**Comment by vidash50** [comment]
good job

**Review by vidash50 — APPROVED** [review]

**Comment by vidash50** [comment]
good job Ana.

**Pull request merged**
