### PR TITLE
Us 3 user able access files

### PR DESCRIPTION
**Pull request by EllaKoch**
Hi guys,  please review my code. Thanks!

### CODE REVIEW

**Comment by Alex-Cret** [comment]
good

**Review by KatrinSi — APPROVED** [review]

**Review by KatrinSi — APPROVED** [review]

**Review by Alex-Cret — APPROVED** [review]

**Review by marwansubhi — APPROVED** [review]
Looking good

**Comment by KatrinSi** [comment]
All seems good to me!

**Review by ayderham — APPROVED** [review]
nice

**Pull request merged**
