### PR TITLE
Us 7 user able to search

### PR DESCRIPTION
**Pull request by EllaKoch**

### CODE REVIEW

**Comment by shiringeldiyeva** [comment]
Great job Elvira

**Comment by EllaKoch** [comment]
Thank you Shirin!

**Comment by davisduane** [comment]
Good job

**Review by davisduane — APPROVED** [review]
Acceptable

**Comment by EllaKoch** [comment]
Thank you Duane!

**Review by vidash50 — APPROVED** [review]

**Review by marwansubhi — APPROVED** [review]
Looks good

**Review by miraysir — APPROVED** [review]
Looks great to me!

**Pull request merged**
