### PR TITLE
Changes to the configuration.properties; Created US_8 class

### PR DESCRIPTION
**Pull request by KatrinSi**
Added changes to the configuration.properties file; Created US_8 class Kate

### CODE REVIEW

**Comment by KatrinSi** [comment]
Please, review my pull request

**Review by EllaKoch — APPROVED** [review]
Looks good, Kate!

**Review by marwansubhi — APPROVED** [review]
Good to go.

**Review by Alex-Cret — APPROVED** [review]
Good job!

**Comment by KatrinSi** [comment]
Guys, when I will merge my pull request then **the property.configuration** file will change. 
I added all 4 users names and 2 more environments(urls). 
Since it might be a breaking change, please, make sure that your code works with a new data. @Alex-Cret @marwansubhi @EllaKoch @vidash50 @davisduane @miraysir @Agalar77 @anitastati @ayderham @aliya-guliyeva @Innakqa @shiringeldiyeva 
Screen Shot 2021-02-07 at 8 33 01 PM

**Comment by EllaKoch** [comment]
👍 thanks for letting me know!

**Review by vidash50 — APPROVED** [review]

**Pull request merged**
