### PR TITLE
Us 7 user able to search

### PR DESCRIPTION
**Pull request by EllaKoch**
Minor change: changed the environment to urlQA2

### CODE REVIEW

**Comment by KatrinSi** [comment]
Great job Elvira!

**Review by KatrinSi — APPROVED** [review]

**Review by anitastati — APPROVED** [review]
Looks Great!

**Comment by ayderham** [comment]
good job

**Review by ayderham — APPROVED** [review]
nice

**Review by marwansubhi — APPROVED** [review]
Looking good

**Pull request merged**
